location ~ ^/index\.php(/|$) {
    try_files @fallback =404;
    fastcgi_pass 127.0.0.1:9000;
    fastcgi_split_path_info ^(.+\.php)(/.*)$;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $realpath_root/public/index.php;
    fastcgi_param DOCUMENT_ROOT $realpath_root;
    fastcgi_param HTTPS on;
}

location / {
    try_files $uri @fallback;
}

location @fallback {
    rewrite ^(.*)$ /index.php?path=$1 last;
}
