services:
  - type: web
    name: ojt-system-backend
    env: php
    plan: free
    buildCommand: composer install && npm install && npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: OJT-System
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: DATABASE_URL
        fromDatabase:
          name: ojt-db
          property: connectionString
      - key: CACHE_DRIVER
        value: redis
      - key: QUEUE_CONNECTION
        value: redis
      - key: REDIS_URL
        fromService:
          name: ojt-redis
          property: connectionString

  - type: pserv
    name: ojt-redis
    env: redis
    plan: free
    ipAllowList: []

databases:
  - name: ojt-db
    engine: postgres
    plan: free
    ipAllowList: []
